name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write      # This is required for creating tags and releases
  issues: write        # This is required if you're using the github plugin
  pull-requests: write # This is required if you're using the github plugin

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # This is important
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          
      - name: Install dependencies
        run: npm install
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release